version: "2"
services:
  node:
    image: "node:18"
    user: "node"
    working_dir: /app
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./:/app
    links:
      - postgres
    build: .
    expose:
      - "3000"
    command: ['npm', 'start']
  postgres:
  # mdillon/postgis is postgres + PostGIS (only). if you need additional
  # extensions, it's probably time to create a purpose-built image with all
  # necessary extensions. sorry, and thanks for adding support for them!
    image: "postgres:14.1-alpine"
    restart: always
    container_name: "typeorm-postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    volumes:
      - database-data:/var/lib/postgresql/data
volumes:
  database-data: {}